/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import card.Card;
import card_supplier.CardSupplier;
import card_supplier.CategoryCardSupplier;
import card_supplier.ClientCardSupplier;
import card_supplier.ProductCardSupplier;
import card_supplier.SaleCardSupplier;
import card_supplier.SupplierCardSupplier;
import card_supplier.UserCardSupplier;
import component.GenericAddFrame;
import component.GenericQueryFrame;
import form.CategoryForm;
import form.ClientForm;
import form.Form;
import form.ProductForm;
import form.SaleForm;
import form.SupplierForm;
import form.UserForm;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.Optional;
import java.util.function.Supplier;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import record.ProductRecord;
import util.EntityHeaderData;
import util.EntityField;
import util.functional.DatabaseErrorProneSupplier;
import record.Record;
import record.SupplierRecord;
import record.UserRecord;
import util.functional.DatabaseErrorProneFunction;
import java.util.Arrays;
import record.CategoryRecord;
import record.ClientRecord;
import record.SaleRecord;

/**
 *
 * @author Edgar
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form formMenu
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        jPanel1 = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jPanel4 = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        headingRegular = new typography.TypographyHeadingRegular();
        textRegular = new typography.TypographyTextRegular();
        jSeparator1 = new javax.swing.JSeparator();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jPanel2 = new javax.swing.JPanel();
        categoryButton = new javax.swing.JButton();
        clientButton = new javax.swing.JButton();
        productButton = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        typographyLabelRegular4 = new typography.TypographyLabelRegular();
        typographyLabelRegular5 = new typography.TypographyLabelRegular();
        typographyLabelRegular6 = new typography.TypographyLabelRegular();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jPanel3 = new javax.swing.JPanel();
        saleButton = new javax.swing.JButton();
        supplierButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        typographyLabelRegular1 = new typography.TypographyLabelRegular();
        typographyLabelRegular2 = new typography.TypographyLabelRegular();
        typographyLabelRegular3 = new typography.TypographyLabelRegular();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú de inicio");

        jPanel1.setBackground(util.ProjectColor.WHITE.getColor());
        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel1.add(filler11, gridBagConstraints);

        jPanel4.setBackground(util.ProjectColor.WHITE.getColor());
        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(filler9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel4.add(filler10, gridBagConstraints);

        headingRegular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingRegular.setText("¡Bienvenido de vuelta!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(headingRegular, gridBagConstraints);

        textRegular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textRegular.setText("Selecciona una de las siguientes categorías para empezar a explorar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(textRegular, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jSeparator1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel1.add(filler8, gridBagConstraints);

        jPanel2.setBackground(util.ProjectColor.WHITE.getColor());
        jPanel2.setLayout(new java.awt.GridBagLayout());

        categoryButton.setBackground(util.ProjectColor.WHITE.getColor());
        categoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64-category.png"))); // NOI18N
        categoryButton.setToolTipText("Categoría");
        categoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        categoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(categoryButton, gridBagConstraints);

        clientButton.setBackground(util.ProjectColor.WHITE.getColor());
        clientButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64-client.png"))); // NOI18N
        clientButton.setToolTipText("Cliente");
        clientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(clientButton, gridBagConstraints);

        productButton.setBackground(util.ProjectColor.WHITE.getColor());
        productButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64-product.png"))); // NOI18N
        productButton.setToolTipText("Producto");
        productButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(productButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel2.add(filler2, gridBagConstraints);

        typographyLabelRegular4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typographyLabelRegular4.setText("Categoría");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(typographyLabelRegular4, gridBagConstraints);

        typographyLabelRegular5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typographyLabelRegular5.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(typographyLabelRegular5, gridBagConstraints);

        typographyLabelRegular6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typographyLabelRegular6.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(typographyLabelRegular6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel1.add(filler4, gridBagConstraints);

        jPanel3.setBackground(util.ProjectColor.WHITE.getColor());
        jPanel3.setLayout(new java.awt.GridBagLayout());

        saleButton.setBackground(util.ProjectColor.WHITE.getColor());
        saleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64-sale.png"))); // NOI18N
        saleButton.setToolTipText("Venta");
        saleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(saleButton, gridBagConstraints);

        supplierButton.setBackground(util.ProjectColor.WHITE.getColor());
        supplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64-supplier.png"))); // NOI18N
        supplierButton.setToolTipText("Proveedor");
        supplierButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supplierButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        supplierButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        supplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(supplierButton, gridBagConstraints);

        userButton.setBackground(util.ProjectColor.WHITE.getColor());
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64-user.png"))); // NOI18N
        userButton.setToolTipText("Usuario");
        userButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(userButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        jPanel3.add(filler6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel3.add(filler7, gridBagConstraints);

        typographyLabelRegular1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typographyLabelRegular1.setText("Venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(typographyLabelRegular1, gridBagConstraints);

        typographyLabelRegular2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typographyLabelRegular2.setText("Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(typographyLabelRegular2, gridBagConstraints);

        typographyLabelRegular3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typographyLabelRegular3.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(typographyLabelRegular3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel1.add(filler5, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButtonActionPerformed
        // id, nombre
        showEntityQueryFrame(
                EntityHeaderData.CATEGORY, 
                (Optional<CategoryRecord> value) -> new CategoryForm(value), 
                (DatabaseErrorProneSupplier<CategoryForm> callback) -> 
                        new GenericAddFrame(EntityHeaderData.CATEGORY, callback),
                (DatabaseErrorProneFunction<Optional<CategoryRecord>, GenericAddFrame> callback) -> 
                        new CategoryCardSupplier(new LinkedList<EntityField>(Arrays.asList(
                                new EntityField("categoria.id", "Id"),
                                new EntityField("categoria.nombre", "Nombre")
                        )), callback)
        );
    }//GEN-LAST:event_categoryButtonActionPerformed

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        showEntityQueryFrame(
                EntityHeaderData.CLIENT, 
                (Optional<ClientRecord> value) -> new ClientForm(value), 
                (DatabaseErrorProneSupplier<ClientForm> callback) -> 
                        new GenericAddFrame(EntityHeaderData.CLIENT, callback),
                (DatabaseErrorProneFunction<Optional<ClientRecord>, GenericAddFrame> callback) -> 
                        new ClientCardSupplier(new LinkedList<EntityField>(Arrays.asList(
                                new EntityField("cliente.id", "Id"),
                                new EntityField("cliente.nombre", "Nombre"),
                                new EntityField("cliente.estado", "Estado"),
                                new EntityField("cliente.municipio", "Municipio"),
                                new EntityField("ventas_por_cliente.ventas_por_cliente", "Ventas")
                        )), callback)
        );
    }//GEN-LAST:event_clientButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // id, nombre y tipo
        // id
        showEntityQueryFrame(
                EntityHeaderData.USER, 
                (Optional<UserRecord> value) -> new UserForm(value), 
                (DatabaseErrorProneSupplier<UserForm> callback) -> 
                        new GenericAddFrame(EntityHeaderData.USER, callback),
                (DatabaseErrorProneFunction<Optional<UserRecord>, GenericAddFrame> callback) -> 
                        new UserCardSupplier(EntityField.of("id", "nombre", "rfc"), callback)
        );
    }//GEN-LAST:event_userButtonActionPerformed

    private void supplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonActionPerformed
        // TODO add your handling code here:
        showEntityQueryFrame(
                EntityHeaderData.SUPPLIER, 
                (Optional<SupplierRecord> value) -> 
                        new SupplierForm(value), 
                (DatabaseErrorProneSupplier<SupplierForm> callback) -> 
                        new GenericAddFrame(EntityHeaderData.SUPPLIER, callback),
                (DatabaseErrorProneFunction<Optional<SupplierRecord>, GenericAddFrame> callback) -> 
                        new SupplierCardSupplier(EntityField.of("id", "nombre", "rfc"), callback)
        );
    }//GEN-LAST:event_supplierButtonActionPerformed

    private void productButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonActionPerformed
        showEntityQueryFrame(
                EntityHeaderData.PRODUCT, 
                (Optional<ProductRecord> value) -> new ProductForm(value), 
                (DatabaseErrorProneSupplier<ProductForm> callback) -> 
                        new GenericAddFrame(EntityHeaderData.PRODUCT, callback),
                (DatabaseErrorProneFunction<Optional<ProductRecord>, GenericAddFrame> callback) -> 
                        new ProductCardSupplier(new LinkedList<EntityField>(Arrays.asList(
                                new EntityField("id"),
                                new EntityField("producto.nombre", "Nombre"),
                                new EntityField("categoria.nombre", "Categoría"),
                                new EntityField("proveedor.nombre", "Proveedor"),
                                new EntityField("codigo", "Código"),
                                new EntityField("precio"),
                                new EntityField("stock")
                        )), callback)
        );
    }//GEN-LAST:event_productButtonActionPerformed

    private void saleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleButtonActionPerformed
        showEntityQueryFrame(
                EntityHeaderData.SALE, 
                (Optional<SaleRecord> value) -> 
                        new SaleForm(value), 
                (DatabaseErrorProneSupplier<SaleForm> callback) -> 
                        new GenericAddFrame(EntityHeaderData.SALE, callback),
                (DatabaseErrorProneFunction<Optional<SaleRecord>, GenericAddFrame> callback) -> 
                        new SaleCardSupplier(new LinkedList<EntityField>(Arrays.asList(
                            new EntityField("venta.id", "Id"),
                            new EntityField("cliente.nombre", "Cliente"),
                            new EntityField("producto.nombre", "Producto"),
                            new EntityField("detalle.cantidad_de_producto", "Cantidad de Producto"),
                            new EntityField("venta.fecha", "Fecha")
                        )), callback)
        );
    }//GEN-LAST:event_saleButtonActionPerformed
    
    protected <
        RecordType extends Record,
        CardType extends Card<RecordType>,
        FormType extends Form<RecordType>
    > void showEntityQueryFrame(
            EntityHeaderData entityHeaderData,
            DatabaseErrorProneFunction<Optional<RecordType>, FormType> formFunction,
            DatabaseErrorProneFunction<DatabaseErrorProneSupplier<FormType>, GenericAddFrame> addFrameFunctionGenerator,
            DatabaseErrorProneFunction<DatabaseErrorProneFunction<Optional<RecordType>, GenericAddFrame>, CardSupplier<RecordType, CardType>> cardSupplierFunction
    ) {
        try {
            GenericQueryFrame<RecordType, CardType, FormType> frame = new GenericQueryFrame(
                    entityHeaderData,
                    formFunction,
                    addFrameFunctionGenerator,
                    cardSupplierFunction
            );
            frame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Un error interno de la aplicación impide que se puedan visualizar los regisros de los usuarios", "Error interno", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Algo salió mal con la base de datos y no se pueden visualizar los registros de los usuarios", "Error de base de datos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    public JButton getCategoryButton() {
        return categoryButton;
    }

    public JButton getClientButton() {
        return clientButton;
    }

    public JButton getProductButton() {
        return productButton;
    }

    public JButton getSaleButton() {
        return saleButton;
    }

    public JButton getSupplierButton() {
        return supplierButton;
    }

    public JButton getUserButton() {
        return userButton;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton categoryButton;
    public javax.swing.JButton clientButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private typography.TypographyHeadingRegular headingRegular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JButton productButton;
    public javax.swing.JButton saleButton;
    public javax.swing.JButton supplierButton;
    private typography.TypographyTextRegular textRegular;
    private typography.TypographyLabelRegular typographyLabelRegular1;
    private typography.TypographyLabelRegular typographyLabelRegular2;
    private typography.TypographyLabelRegular typographyLabelRegular3;
    private typography.TypographyLabelRegular typographyLabelRegular4;
    private typography.TypographyLabelRegular typographyLabelRegular5;
    private typography.TypographyLabelRegular typographyLabelRegular6;
    public javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
