/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import component.SearchField;

/**
 *
 * @author Edgar
 */
public class QueryFrame extends javax.swing.JFrame {

    /**
     * Creates new form FrameConsultas
     */
    public QueryFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PROVEEDOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 230, 66, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "RFC", "Dirección", "Celular", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 28, 394, 88);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripción", "Precio", "Stock", "Categoría", "Proveedor"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 410, 390, 80);

        jLabel2.setText("CLIENTE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 6, 44, 16);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Dirección", "Teléfono", "Celular"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 250, 390, 70);

        jLabel3.setText("PRODUCTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 120, 62, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-proveedor-16.png"))); // NOI18N
        jLabel4.setText("Proveedor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 380, 54, 16);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 380, 120, 22);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-search-16.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(255, 380, 30, 7);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripción", "Precio", "Stock", "Categoría", "Proveedor"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(0, 710, 390, 80);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripción"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(0, 580, 390, 50);

        jLabel5.setText("PRODUCTOS POR PROVEEDOR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 350, 170, 16);

        jLabel6.setText("CATEGORÍA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 560, 70, 16);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripción", "Precio", "Stock", "Categoría", "Proveedor"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(0, 140, 390, 80);

        jLabel7.setText("PRODUCTOS POR CATEGORÍA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 640, 170, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-categoria-16.png"))); // NOI18N
        jLabel8.setText("Categoría");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 670, 51, 16);

        jTextField2.setText("jTextField1");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 670, 120, 22);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-search-16.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 670, 30, 7);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Folio", "Fecha", "Subtotal", "IVA", "Total", "Cliente"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(0, 920, 380, 190);

        jLabel9.setText("Folio");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 870, 26, 16);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(10, 890, 71, 22);

        jTextField4.setText("jTextField3");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(90, 890, 71, 22);

        jLabel10.setText("VENTAS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 830, 42, 16);

        jLabel11.setText("Fecha fin");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 870, 63, 16);

        jTextField5.setText("jTextField3");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 890, 71, 22);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 890, 75, 23);

        jLabel12.setText("Fecha inicio");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 870, 63, 16);

        jMenu1.setText("File");

        jMenu3.setText("Cliente");

        jMenuItem1.setText("Cliente más frecuente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Cliente menos frecuente");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Cliente mayor compra");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Cliente menor compra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem9.setText("Lista de clientes");
        jMenu3.add(jMenuItem9);

        jMenu1.add(jMenu3);

        jMenu5.setText("Producto");

        jMenuItem5.setText("Producto más vendido");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Producto menos vendido");
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Producto de menor costo");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Producto de mayor costo");
        jMenu5.add(jMenuItem8);

        jMenuItem10.setText("Lista de productos");
        jMenu5.add(jMenuItem10);

        jMenu1.add(jMenu5);

        jMenu6.setText("Proveedor");

        jMenuItem11.setText("Lista de proveedores");
        jMenu6.add(jMenuItem11);

        jMenuItem12.setText("Productos por proveedor");
        jMenu6.add(jMenuItem12);

        jMenu1.add(jMenu6);

        jMenu7.setText("Venta");

        jMenuItem13.setText("Mayor venta");
        jMenu7.add(jMenuItem13);

        jMenuItem14.setText("Menor venta");
        jMenu7.add(jMenuItem14);

        jMenuItem15.setText("Fecha de mayor venta");
        jMenu7.add(jMenuItem15);

        jMenuItem16.setText("Fecha de menor venta");
        jMenu7.add(jMenuItem16);

        jMenuItem17.setText("Ventas por fecha");
        jMenu7.add(jMenuItem17);

        jMenu1.add(jMenu7);

        jMenu8.setText("Categoría");

        jMenuItem18.setText("Lista de categorías");
        jMenu8.add(jMenuItem18);

        jMenuItem19.setText("Productos por categoría");
        jMenu8.add(jMenuItem19);

        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu4.setText("jMenu4");
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * public class Querier<K>
     *  protected Optional<Field> orderBy
     *  protected Optional<Integer> limitBy
     *  protected Optional<Pair<Field, String>> search;
     * 
     * public class QueryFrame<K>
     *  public <K> QueryFrame()
     *  
     *  protected Querier<K> querier;
     * 
     * 
     * public class Schema
     *  public LinkedList<Field> getFields()
     * 
     * A Schema should be tied to a Card that can render it
     * 
     * public class Entity<K extends Schema>
     * public class Card<K extends Schema>
     *  public Card(Entity<K> entity)
     * 
     * 
     * OrderBy
     * LimitBy
     * FindBy
     * 
     */
    
    /**
     * 
     * @param evt 
     */
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
