/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

/**
 *
 * @author Edgar
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form formMenu
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clientButton = new javax.swing.JButton();
        productButton = new javax.swing.JButton();
        supplierButton = new javax.swing.JButton();
        categoryButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        salesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        clientButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img-cliente-64.png"))); // NOI18N
        clientButton.setToolTipText("Cliente");
        clientButton.setBorderPainted(false);
        clientButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clientButton);

        productButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img-producto-64.png"))); // NOI18N
        jPanel1.add(productButton);

        supplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img-proveedor-64.png"))); // NOI18N
        supplierButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        supplierButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(supplierButton);

        categoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img-categoria-64.png"))); // NOI18N
        jPanel1.add(categoryButton);

        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img-usuario-64.png"))); // NOI18N
        jPanel1.add(userButton);

        salesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img-venta-64.png"))); // NOI18N
        jPanel1.add(salesButton);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 400, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton categoryButton;
    public javax.swing.JButton clientButton;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton productButton;
    public javax.swing.JButton salesButton;
    public javax.swing.JButton supplierButton;
    public javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
