/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package card;

import component.GenericAddFrame;
import java.util.Optional;
import record.ClientRecord;
import util.TextFormatting;
import util.functional.DatabaseErrorProneFunction;

/**
 *
 * @author Edgar
 */
public class ClientCard extends Card<ClientRecord> {
    public ClientCard() {
        super();
    }

    public ClientCard(Optional<ClientRecord> currentRecord, DatabaseErrorProneFunction<Optional<ClientRecord>, GenericAddFrame> addFrameFunction) {
        super(currentRecord, addFrameFunction);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardHeader = new component.CardHeader();
        addressLabel = new typography.TypographyLabelRegular();
        rfcLabel = new typography.TypographyLabelRegular();
        telephoneNumberLabel = new typography.TypographyLabelRegular();
        cellphoneLabel = new typography.TypographyLabelRegular();
        salesCountLabel = new typography.TypographyLabelRegular();

        setBackground(util.ProjectColor.WHITE.getColor());
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(cardHeader, gridBagConstraints);

        addressLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-home.png"))); // NOI18N
        addressLabel.setText("typographyLabelRegular1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(addressLabel, gridBagConstraints);

        rfcLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-barcode.png"))); // NOI18N
        rfcLabel.setText("typographyLabelRegular2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(rfcLabel, gridBagConstraints);

        telephoneNumberLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-call.png"))); // NOI18N
        telephoneNumberLabel.setText("typographyLabelRegular2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(telephoneNumberLabel, gridBagConstraints);

        cellphoneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-ad-units.png"))); // NOI18N
        cellphoneLabel.setText("typographyLabelRegular2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(cellphoneLabel, gridBagConstraints);

        salesCountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-functions.png"))); // NOI18N
        salesCountLabel.setText("typographyLabelRegular2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(salesCountLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void initializeComponents() {
        initComponents();
    }

    @Override
    public void updateInterfaceForCurrentRecord() {
        ClientRecord record = currentRecord.get();
        
        addressLabel.setText(TextFormatting.formatAddress(
                record.getCalle(), 
                record.getNumero_de_casa(), 
                record.getColonia(), 
                record.getMunicipio(), 
                record.getEstado()
        ));
        rfcLabel.setText(record.getRfc());
        
        telephoneNumberLabel.setText(TextFormatting.formatPhoneNumber(record.getTelefono()));
        cellphoneLabel.setText(TextFormatting.formatPhoneNumber(record.getCelular()));
        
        cardHeader.setData(record.getNombre(), record.getId());
        
        salesCountLabel.setText(TextFormatting.formatUnits(record.getVentasRealizadas(), "venta", "ventas"));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private typography.TypographyLabelRegular addressLabel;
    private component.CardHeader cardHeader;
    private typography.TypographyLabelRegular cellphoneLabel;
    private typography.TypographyLabelRegular rfcLabel;
    private typography.TypographyLabelRegular salesCountLabel;
    private typography.TypographyLabelRegular telephoneNumberLabel;
    // End of variables declaration//GEN-END:variables
}
