/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package card;

import component.GenericAddFrame;
import form.Form;
import java.util.Optional;
import record.ProductRecord;
import util.EntityHeaderData;
import util.TextFormatting;
import util.functional.DatabaseErrorProneFunction;

/**
 *
 * @author Edgar
 */
public class ProductCard extends Card<ProductRecord> {

    public ProductCard() {
        super();
    }

    public ProductCard(Optional<ProductRecord> currentRecord, DatabaseErrorProneFunction<Optional<ProductRecord>, GenericAddFrame> addFrameSupplier) {
        super(currentRecord, addFrameSupplier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        cardHeader = new component.CardHeader();
        categoryText = new component.LabeledText();
        supplierText = new component.LabeledText();
        priceLabel = new typography.TypographyLabelRegular();
        discountLabel = new typography.TypographyLabelRegular();
        stockLabel = new typography.TypographyLabelRegular();
        codeLabel = new typography.TypographyLabelRegular();
        soldProductsLabel = new typography.TypographyLabelRegular();

        setBackground(util.ProjectColor.WHITE.getColor());
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(filler5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(cardHeader, gridBagConstraints);

        categoryText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24-category.png"))); // NOI18N
        categoryText.setLabel("Categoría");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(categoryText, gridBagConstraints);

        supplierText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24-supplier.png"))); // NOI18N
        supplierText.setLabel("Proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(supplierText, gridBagConstraints);

        priceLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-paid.png"))); // NOI18N
        priceLabel.setText("$500");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(priceLabel, gridBagConstraints);

        discountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-percent.png"))); // NOI18N
        discountLabel.setText("50%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(discountLabel, gridBagConstraints);

        stockLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-functions.png"))); // NOI18N
        stockLabel.setText("50 unidades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(stockLabel, gridBagConstraints);

        codeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-barcode.png"))); // NOI18N
        codeLabel.setText("1234789");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(codeLabel, gridBagConstraints);

        soldProductsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12-functions.png"))); // NOI18N
        soldProductsLabel.setText("50 vendidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(soldProductsLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void initializeComponents() {
        initComponents();
    }

    @Override
    public void updateInterfaceForCurrentRecord() {
        if (currentRecord.isPresent()) {
            cardHeader.setData(currentRecord.get().getNombre(), currentRecord.get().getId());
            priceLabel.setText(TextFormatting.formatCurrency(currentRecord.get().getPrecio()));
            discountLabel.setText(TextFormatting.formatPercentage(currentRecord.get().getDescuento()));
            stockLabel.setText(TextFormatting.formatUnits(currentRecord.get().getStock(), "existente", "existentes"));
            codeLabel.setText(currentRecord.get().getCodigo());
            
            categoryText.setContent(currentRecord.get().getCategoria().getPrettyName());
            supplierText.setContent(currentRecord.get().getProveedor().getPrettyName());
            soldProductsLabel.setText(TextFormatting.formatUnits(currentRecord.get().getProductosVendidos(), "vendido", "vendidos"));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.CardHeader cardHeader;
    private component.LabeledText categoryText;
    private typography.TypographyLabelRegular codeLabel;
    private typography.TypographyLabelRegular discountLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private typography.TypographyLabelRegular priceLabel;
    private typography.TypographyLabelRegular soldProductsLabel;
    private typography.TypographyLabelRegular stockLabel;
    private component.LabeledText supplierText;
    // End of variables declaration//GEN-END:variables
}
