/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package card;

import component.GenericAddFrame;
import java.util.Optional;
import record.SaleRecord;
import util.functional.DatabaseErrorProneFunction;

/**
 *
 * @author Edgar
 */
public class SaleCard extends Card<SaleRecord> {

    public SaleCard() {
        super();
    }

    public SaleCard(Optional<SaleRecord> currentRecord, DatabaseErrorProneFunction<Optional<SaleRecord>, GenericAddFrame> addFrameFunction) {
        super(currentRecord, addFrameFunction);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardHeader = new component.CardHeader();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        clientText = new component.LabeledText();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        folioLabel = new typography.TypographyLabelRegular();
        dateLabel = new typography.TypographyLabelRegular();

        setBackground(util.ProjectColor.WHITE.getColor()
        );
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(cardHeader, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        add(filler3, gridBagConstraints);

        clientText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24-client.png"))); // NOI18N
        clientText.setLabel("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(clientText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        add(filler1, gridBagConstraints);

        folioLabel.setText("typographyLabelRegular1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(folioLabel, gridBagConstraints);

        dateLabel.setText("typographyLabelRegular1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(dateLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.CardHeader cardHeader;
    private component.LabeledText clientText;
    private typography.TypographyLabelRegular dateLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private typography.TypographyLabelRegular folioLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initializeComponents() {
        initComponents();
        System.out.println("The current id is: " + currentRecord.get().getId());
    }

    @Override
    public void updateInterfaceForCurrentRecord() {
        SaleRecord record = currentRecord.get();
        cardHeader.setData(record.getFecha().toString(), record.getId());
        clientText.setContent(record.getCliente().getPrettyName());
        folioLabel.setText(String.valueOf(record.getFolio()));
        dateLabel.setText(record.getFecha().toString());
    }
}
