/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import javax.swing.ImageIcon;
import utils.EntityControlData;

/**
 *
 * @author Edgar
 */
public class EntityHeader extends javax.swing.JPanel {
    protected final EntityControlData data;
    
    
    /**
     * Creates new form EntityHeader
     */
    public EntityHeader() {
        this(EntityControlData.CATEGORY);
    }
    
    public EntityHeader(EntityControlData data) {
        this.data = data;
        
        initComponents();
        
        nameLabel.setText(data.getInternalName());
        iconLabel.setIcon(new ImageIcon(getClass().getResource("/images/" + data.getIconName())));
        banner.setBackground(data.getColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        banner = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(utils.ProjectColors.WHITE.getColor());
        setMinimumSize(new java.awt.Dimension(400, 150));
        setPreferredSize(new java.awt.Dimension(400, 150));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/64-product.png"))); // NOI18N
        add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        nameLabel.setFont(new java.awt.Font("Inter 28pt ExtraBold", 0, 36)); // NOI18N
        nameLabel.setForeground(utils.ProjectColors.BLACK.getColor());
        nameLabel.setText("Producto");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        banner.setBackground(new java.awt.Color(14, 165, 233));
        banner.setPreferredSize(new java.awt.Dimension(400, 30));

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 340, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
