/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import javax.swing.Icon;

/**
 *
 * @author Edgar
 */
public class LabeledText extends javax.swing.JPanel {

    /**
     * Creates new form LabeledText
     */
    public LabeledText() {
        this("Label", "Content", null);
    }
    
    public LabeledText(String label, String content, Icon icon) {
        initComponents();
        
        this.labelElement.setText(label);
        this.contentElement.setText(content);
        this.labelElement.setIcon(icon);
    }
    
    public Icon getIcon() {
        return this.labelElement.getIcon();
    }
    
    public void setIcon(Icon icon) {
        this.labelElement.setIcon(icon);
    }
    
    public String getContent() {
        return contentElement.getText();
    }
    
    public String getLabel() {
        return labelElement.getText();
    }
    
    public void setContent(String content) {
        this.contentElement.setText(content);
    }
    
    public void setLabel(String label) {
        this.labelElement.setText(label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelElement = new typography.TypographyTextRegular();
        contentElement = new typography.TypographyLabelRegular();

        setBackground(util.ProjectColor.WHITE.getColor()
        );
        setLayout(new java.awt.GridBagLayout());

        labelElement.setText("Label");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(labelElement, gridBagConstraints);

        contentElement.setText("Content");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(contentElement, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private typography.TypographyLabelRegular contentElement;
    private typography.TypographyTextRegular labelElement;
    // End of variables declaration//GEN-END:variables
}
