/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Edgar
 */
public class LabeledTextField extends javax.swing.JPanel {
    protected String labelText = "";
    
    /**
     * Creates new form LabeledTextField
     */
    public LabeledTextField() {
        this("Label");
    }
    
    
    public LabeledTextField(String labelText) {
        initComponents();
        this.labelElement.setText(labelText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelElement = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();

        setBackground(util.ProjectColor.WHITE.getColor());
        setLayout(new java.awt.GridBagLayout());

        labelElement.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        labelElement.setText("Etiqueta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(labelElement, gridBagConstraints);

        textField.setFont(new java.awt.Font("Open Sans Medium", 0, 15)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(textField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setLabelText(String labelText) {
        this.labelText = labelText;
        this.labelElement.setText(labelText);
    }
    
    public String getLabelText() {
        return labelText;
    }

    public JTextField getTextField() {
        return textField;
    }
    
    public String getText() {
        return textField.getText();
    }
    
    @Override
    public void setEnabled(boolean enabled) {
        textField.setEnabled(enabled);
    }
    
    @Override
    public boolean isEnabled() {
        return textField.isEnabled();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelElement;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
