/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Edgar
 * @param <ItemType>
 */
public class LabeledComboBox<ItemType> extends javax.swing.JPanel {
    protected String labelText;
    protected DefaultComboBoxModel<ItemType> model;
    protected int selectedIndex;
    
    /**
     * Creates new form LabeledComboBox
     */
    public LabeledComboBox() {
        this("Label", (DefaultComboBoxModel<ItemType>) new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }), 0);
    }

    public LabeledComboBox(String labelText, DefaultComboBoxModel<ItemType> model, int selectedIndex) {
        initComponents();
        setLabelText(labelText);
        setModel(model);
        setSelectedIndex(selectedIndex);
    }

    public String getLabelText() {
        return labelText;
    }

    public void setLabelText(String labelText) {
        this.labelText = labelText;
        this.labelElement.setText(labelText);
    }

    public DefaultComboBoxModel<ItemType> getModel() {
        return model;
    }

    public void setModel(DefaultComboBoxModel<ItemType> model) {
        this.model = model;
        this.comboBox.setModel(model);
    }

    public int getSelectedIndex() {
        return selectedIndex;
    }

    public void setSelectedIndex(int selectedIndex) {
        this.selectedIndex = selectedIndex;
        this.comboBox.setSelectedIndex(selectedIndex);
    }

    public JComboBox<ItemType> getComboBox() {
        return comboBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelElement = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();

        setBackground(util.ProjectColors.WHITE.getColor());
        setLayout(new java.awt.GridBagLayout());

        labelElement.setFont(new java.awt.Font("Open Sans Light", 0, 12)); // NOI18N
        labelElement.setText("Label");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(labelElement, gridBagConstraints);

        comboBox.setBackground(util.ProjectColors.WHITE.getColor()
        );
        comboBox.setFont(new java.awt.Font("Open Sans Medium", 0, 15)); // NOI18N
        comboBox.setForeground(util.ProjectColors.BLACK.getColor()
        );
        comboBox.setModel(new DefaultComboBoxModel<ItemType>());
        comboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(comboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ItemType> comboBox;
    private javax.swing.JLabel labelElement;
    // End of variables declaration//GEN-END:variables
}
